import { createUseStyles, ThemeProvider, useTheme } from "react-jss";

export const styles = createUseStyles((theme) => ({
  pmainWrapper: {
    background: theme.color.grey,
    height: "978px",
    margin: "70px 150px 70px 150px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  contentWrapper: {
    width: "90%",
    height: "708px",
    display: "flex",
    gap: "50px",
    padding: "28px",
  },
  pleftWrapper: {
    display: "flex",
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    alignItems: "center",
    gap: "70px",
    width: "50%",
    height: "100%",
  },
  prightWrapper: {
    width: "50%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  pcontent: {
    width: "80%",
  },
  psslHeader: {
    fontFamily: "Aeonik",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "49px",
    lineHeight: "59px",
  },
  psslP: {
    fontFamily: "Aeonik",
    fontStyle: "normal",
    fontzseight: 300,
    fontSize: "15px",
    lineHeight: "24px",
    color: theme.color.lightGrey,
  },
  psslButton: {
    background: theme.color.lightRed,
    border: "none",
    borderRadius: "4px",
    flexDirection: "row",
    alignItems: "center",
    padding: "12px 24px",
    gap: "8px",
    cursor: "pointer",
  },
  psslBtnText: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "10px",
    lineHeight: "12px",
    color: theme.color.white,
    fontSize: "16px",
    lineHeight: "24px",
    textAlign: "center",
  },
  pcolumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "70px",
  },
  prow: {
    margin: "auto",
  },
}));
