import { createUseStyles, ThemeProvider, useTheme } from "react-jss";

export const styles = createUseStyles((theme) => ({
  ModalMiddleMainWrapper: {
    borderRadius: 3.23941,
    height: 411,
  },
  ModalMiddleContanier: {
    backgroundColor: theme.color.buttonPink,
    border: "0.809851px solid #ED3957",
    margin: "52px 24px 79px 24px",
    display: "flex",
    position: "relative",
  },
  ModalMiddleicon1: {
    position: "absolute",
    left: "1.65%",
    right: "96.65%",
    top: "6.87%",
    bottom: "86.6%",
  },
  ModalMiddleicon2: {
    position: "absolute",
    left: "48.53%",
    right: "49.12%",
    top: "6.87%",
    bottom: "80.27%",
  },
  ModalMiddleicon3: {
    top: "85.6%",
    left: "51.18%",
    right: "41.23%",
    bottom: "4.81%",
    position: "absolute",
  },

  ModalMiddleleft: {
    margin: "48px 0px 18px 50px",
    width: "80%",
  },
  ModalMiddleright: {},
  ModalMiddleTextWrapper: {
    width: 432,
    height: 123,
  },
  ModalMiddleTextPara: {
    fontFamily: theme.font.firstfont,
    fontWeight: theme.Weight.medium,
    fontSize: theme.size.thirdSize,
    color: theme.color.lightBlack,
    margin: 0,
    lineHeight: "28px",
  },
  ModalMiddleTextHead: {
    fontFamily: theme.font.firstfont,
    fontWeight: theme.Weight.bold,
    fontSize: theme.size.ninethSize,
    color: theme.color.lightBlack,
    lineHeight: "45px",
    margin: 0,
  },
  ModalMiddleButtonsContanier: {
    display: "flex",
    gap: "16px",
    paddingTop: "16px",
  },
  startBuilding: {
    fontFamily: theme.font.secondfont,
    fontWeight: theme.Weight.bold,
    fontSize: theme.size.tenthSize,
    color: theme.color.lightBlack,
    backgroundColor: theme.color.white,
    padding: "12.9576px 25.9152px",
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    textAlign: "right",
    border: 0,
    cursor: "pointer",
  },
  explore: {
    fontFamily: theme.font.secondfont,
    fontWeight: theme.Weight.bold,
    fontSize: theme.size.tenthSize,
    color: theme.color.lightBlack,
    backgroundColor: theme.color.buttonPink,
    padding: "12.9576px 25.9152px",
    border: `1px solid ${theme.color.white}`,
    borderRadius: 3.23941,
    display: "flex",
    alignItems: "center",
    textAlign: "right",
    cursor: "pointer",
  },
}));
