import { createUseStyles, ThemeProvider, useTheme } from "react-jss";

export const styles = createUseStyles((theme) => ({
  main_wrapper: {
    width:"100%",
    height:69,
    backgroundColor: theme.color.black,
  },
  own_wrapper: {
    display:"flex",
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"center",
    padding:"0px",
    gap:"20px",
  },
  own: {
    fontFamily: "Aeonik",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "20px",
    lineHeight: "24px",
    display: "flex",
    alignItems: "center",
    color: theme.color.white,
    paddingTop: "5px",
  },
  own_button: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "9px 16px",
    gap: "10px",
    width: "101px",
    height: "33px",
    background: theme.color.lightPink,
    borderRadius: "4px",
    flex: "none",
    order: 1,
    flexGrow: 0,
    zIndex: 1,
    border: "none",
    cursor: "pointer",
  },
  btn_text: {
    width: "77px",
    height: "17px",
    fontFamily: "vInter",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "17px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.color.lightBlack,
  },
}));
