import { createUseStyles, ThemeProvider, useTheme } from "react-jss";
export const styles = createUseStyles((theme) => ({
  mainWrapper: {
    width: "100%",
    backgroundColor: theme.color.black,
  },
  ownWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    gap: "20px",
  },
  own: {
    fontFamily: theme.font.firstfont,
    fontWeight: theme.Weight.light,
    fontSize: theme.size.fourthSize,
    lineHeight: "24px",
    display: "flex",
    alignItems: "center",
    color: theme.color.white,
  },
  ownButton: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "9px 16px",
    gap: "10px",
    background: theme.color.lightPink,
    borderRadius: "4px",
    flex: "none",
    order: 1,
    flexGrow: 0,
    zIndex: 1,
    border: "none",
    cursor: "pointer",
    "&:hover": {
      opacity: 0.8,
      border: "none",
      cursor: "pointer",
    },
  },
  btnText: {
    fontFamily: theme.font.secondfont,
    fontWeight: theme.Weight.medium,
    fontSize: theme.size.secondSize,
    lineHeight: "17px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.color.lightBlack,
  },
}));
